---
permalink: intro-family.html 
keywords:  
summary:  
---
= NetAppソリューションについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetAppソリューションは、多様な IT 課題に対応するためにカスタマイズされた包括的なリソース スイートを提供します。各ソリューションには適切なコンテンツとツールが組み込まれており、 NetAppテクノロジをビジネスにとって最も重要な方法で活用するのに役立ちます。

ソリューションはテクノロジー領域別に整理されています。



== 仮想化

主要な仮想化プラットフォームとのNetApp統合にアクセスします。管理を合理化し、リソース効率を高め、環境全体のパフォーマンスを最適化します。

link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/["仮想化ソリューションを見る"] 。



== 人工知能（AI）

NetApp の AI ソリューションで機械学習とディープラーニングのワークフローを加速します。  NetAppストレージを一般的な AI フレームワークと統合し、データ パイプラインを最適化し、AI ワークロードを効率的に導入する方法を説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-ai/["AIソリューションを見る"] 。



== パブリッククラウドとハイブリッドクラウド

パブリック、プライベート、ハイブリッド クラウド インフラストラクチャ全体でNetAppソリューションをシームレスに導入および管理します。一貫した運用と俊敏なデータ移動を実現するために、主要なクラウド プロバイダーとの統合を検討してください。

link:https://docs.netapp.com/us-en/netapp-solutions-cloud/["クラウドソリューションを見る"] 。



== データベース

Oracle や SQL Server などのエンタープライズ データベースのストレージとパフォーマンスを最適化します。バックアップ、リカバリ、チューニングのベスト プラクティスにアクセスして、ミッション クリティカルなワークロードの信頼性の高いサポートを確保します。

link:https://docs.netapp.com/us-en/netapp-solutions-databases/["データベースソリューションを表示"] 。



== SAP と SAP HANA

検証済みの設計、パフォーマンス最適化手法、データ保護戦略を検討して、運用を簡素化し、SAP 投資の価値を最大化します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/["SAPソリューションを見る"] 。



== コンテナ

NetAppの永続ストレージおよびデータ管理ソリューションを使用して、コンテナ化されたアプリケーションをサポートします。スケーラビリティと回復力を強化するためのオーケストレーション プラットフォームとの統合戦略について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-containers/["コンテナソリューションを見る"] 。



== データ管理

高性能なデータ ソリューションを使用して、Splunk や Apache Spark などの大規模な分析プラットフォームをサポートします。  NetApp が複雑な分析環境全体でデータの整合性を維持し、パフォーマンスを最適化する方法について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-dataops/["データ管理ソリューションを見る"] 。
